"""initial auth schema

Revision ID: 76812a11191f
Revises:
Create Date: 2026-07-31 14:49:30.290756

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "76812a11191f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The drumgen schema pre-exists on the shared prod instance; create it if
    # missing (fresh dev DB / offline SQL) — idempotent either way.
    op.execute("CREATE SCHEMA IF NOT EXISTS drumgen")
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("avatar_path", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_users_email"), "users", ["email"], unique=True, schema="drumgen"
    )
    op.create_table(
        "auth_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["drumgen.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_subject"),
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_auth_identities_user_id"),
        "auth_identities",
        ["user_id"],
        unique=False,
        schema="drumgen",
    )
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["drumgen.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_email_tokens_token_hash"),
        "email_tokens",
        ["token_hash"],
        unique=True,
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_email_tokens_user_id"),
        "email_tokens",
        ["user_id"],
        unique=False,
        schema="drumgen",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["drumgen.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_sessions_token_hash"),
        "sessions",
        ["token_hash"],
        unique=True,
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="drumgen"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drumgen_sessions_user_id"), table_name="sessions", schema="drumgen")
    op.drop_index(op.f("ix_drumgen_sessions_token_hash"), table_name="sessions", schema="drumgen")
    op.drop_table("sessions", schema="drumgen")
    op.drop_index(
        op.f("ix_drumgen_email_tokens_user_id"), table_name="email_tokens", schema="drumgen"
    )
    op.drop_index(
        op.f("ix_drumgen_email_tokens_token_hash"), table_name="email_tokens", schema="drumgen"
    )
    op.drop_table("email_tokens", schema="drumgen")
    op.drop_index(
        op.f("ix_drumgen_auth_identities_user_id"), table_name="auth_identities", schema="drumgen"
    )
    op.drop_table("auth_identities", schema="drumgen")
    op.drop_index(op.f("ix_drumgen_users_email"), table_name="users", schema="drumgen")
    op.drop_table("users", schema="drumgen")
    # ### end Alembic commands ###
