"""password history

Revision ID: c5b89ae86d48
Revises: 08a958a813be
Create Date: 2026-07-31 21:08:40.183949

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c5b89ae86d48"
down_revision: str | None = "08a958a813be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["drumgen.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_password_history_created_at"),
        "password_history",
        ["created_at"],
        unique=False,
        schema="drumgen",
    )
    op.create_index(
        op.f("ix_drumgen_password_history_user_id"),
        "password_history",
        ["user_id"],
        unique=False,
        schema="drumgen",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_drumgen_password_history_user_id"), table_name="password_history", schema="drumgen"
    )
    op.drop_index(
        op.f("ix_drumgen_password_history_created_at"),
        table_name="password_history",
        schema="drumgen",
    )
    op.drop_table("password_history", schema="drumgen")
    # ### end Alembic commands ###
